### ISSUE TITLE
Bug in Insert CC Events 1-2 (For Selected Notes)

### ISSUE THREAD

**Issue by ARkaine2** [zaibuyidao/ReaScripts#1]
As you can see, sometimes it creates MIDI CCs in wrong way.

![asdasadsad](https://user-images.githubusercontent.com/31447095/77241931-0225fd80-6c02-11ea-89d6-a5131d9acb0c.png)

Can it be fixed?

**Comment by zaibuyidao** [comment]
Yes, it normally handles single-melody instruments. If multiple notes occur at the same start time, REAPER will automatically sort it, so there will be such a problem. I fixed it and now no matter how many notes are at the same start time, they are treated as one note. You can update this script in ReaPack.

**Comment by ARkaine2** [comment]
Thanks a lot for your answer and responsibility.

But now i got another problem.
Probably script "scans" notes in some wrong way, so it make CC points in some strange way between ALL OF NOTES, not on each of the notes.

![ascacscascaca](https://user-images.githubusercontent.com/31447095/77316937-f5dd9580-6d12-11ea-8776-209a3603309c.png)

**Comment by zaibuyidao** [comment]
I tested the script and found no problems. Or am I missing something?

The function of this script is to output the CC value of the selected note in the way of ABABAB ... If the input A is 1, B is 127, the values ​​will be inserted repeatedly in the order of 1 127 1 127 1 127 ... Generally used on some single-melody instruments, such as the left pan is fixed at 1 and the right pan is fixed at 127. Each time you play A and then B, the instrument played according to this rule is effective. Apart from this, it should rarely be used elsewhere.

![](https://www.soundengine.cn/assets/uploads/files/1584971306910-1-2.png)

**Comment by ARkaine2** [comment]
Oh sorry. 
I misunderstood "destination" of this script.

I thout that it can be used for example for Sustain CC (64) or any other controller to make CC value maximum until start of next note.

Something like this:
![ascsacacsac](https://user-images.githubusercontent.com/31447095/77342225-8c707d80-6d38-11ea-8318-d05779bff78c.png)
(but with lesser/customizible "gap")

Can this be done? Thanks for your attention.

**Comment by zaibuyidao** [comment]
OK, try this.
**zaibuyidao_Insert Sustain Pedal (For Selected Notes)**

You can adjust the specific offset value yourself.

**Comment by ARkaine2** [comment]
THANKS A LOT. 
This script made by you is a real life/time-saver. :)
And your responsibility is realy impressive.
You are the best script writer.
