### ISSUE TITLE
Range Wrong in Move Pitch Bend Down One Semitone (Pitch Range 12)

### ISSUE THREAD

**Issue by jonaspeter** [zaibuyidao/ReaScripts#10]
Hi,

there's an error in your script at this line:  https://github.com/zaibuyidao/ReaScripts/blob/2308addbdace96e19aac0136397d2b09435d5238/MIDI%20Editor/zaibuyidao_Move%20Pitch%20Bend%20Down%20One%20Semitone%20(Pitch%20Range%2012).lua#L132

I think this should be 12 instead of 2. 

Thanks for your scripts.

**Comment by zaibuyidao** [comment]
Thanks, fixed.
