### ISSUE TITLE
zaibuyidao_Batch Rename Track

### ISSUE THREAD

**Issue by ARkaine2** [zaibuyidao/ReaScripts#16]
I find this batch-renamer best,
it has minimalistic, Reaper-like interface,
and everything is fine in it.

If i remember correctly, at first launch this script shows some help window, but I closed it once.

Can you please tell how to add counter to (before/after) track names?

**Comment by zaibuyidao** [comment]
Yes, you can find the reaper-extstate.ini file in the REAPER program folder and delete the following content:

[BATCH_RENAME_TRACK]
ShowMsg=false

The help window will appear again.

Alternatively, you can directly use wildcards:
For a numeric-based counter, use v=【number】;
For an alphabetic-based counter, use a=【letter】.

For example, if you want to number track names like this:
TK_03_a
TK_04_b
TK_05_c

You can select the three tracks and use the wildcards:
TK_v=03_a=a

**Comment by ARkaine2** [comment]
[zaibuyidao](https://github.com/zaibuyidao), thanks, that's helpful.
