### ISSUE TITLE
More randomize notes' parameters scripts

### ISSUE THREAD

**Issue by ARkaine2** [zaibuyidao/ReaScripts#4]
I know that it's my not first ask, but you already saved my life and scripts made by you work perfect.
I hope that I won't be too obsessive, but I have some more asks about randomization scripts.
If you do not mind, consider them a continuation of randomization theme.

Here's my asks sorted by priority:

1.
Randomize MIDI Notes

I know some scripts like this, but some of them are complicated while the others don't have desirable functionality, while I need simple useful script, that will:

Randomize MIDI notes in certain and customizible (inside code) range (let's say by default from 1 to 2 octave) that will work without window (via single click -- like scripts from this theme: https://github.com/zaibuyidao/ReaScripts/issues/3).

2.
Random Mute Notes

As told in name.
Maybe with variable chance (in code) or nvm.

And, if possible:

3.
Randomize Notes Position
Like humanize velocity, but only for notes' positions in about ± 3 MIDI ticks.

4. 
Randomize Notes Length
Like humanize velocity, but only for notes' length in about ± 3 MIDI ticks.

I'll be very appreciate.

**Comment by zaibuyidao** [comment]
I don’t quite understand the requirements of the first function,  just move the selected note by 1 or 2 octave?

The other three scripts are implemented, you can download them from ReaPack:
zaibuyidao_Random Mute Notes.lua
zaibuyidao_Random Notes Start (Customize).lua -- Randomize Notes Position
zaibuyidao_Random Notes End (Customize).lua -- Randomize Notes Length

**Comment by ARkaine2** [comment]
> I don’t quite understand the requirements of the first function, just move the selected note by 1 or 2 octave?

Oh no.

I mean randomization that, if possible, will have definible minimum and maximum of range.

I don't know exact numbers of notes, but let's say that note C0 is number 48.
There are twelve notes in each octave, so C1 will be 60 and C2 will be 72.

c0 = 48, c#0 = 49, d0 = 50, d#0 = 51, e0 = 52, f0 = 53, f#0 = 54, g0 = 55, g#0 = 56, a0 = 57, a#0 = 58, b0 = 59
c1 = 60, c#1 = 61, d1 = 62, d#1 = 63, e1 = 64, f1 = 65, f#1 = 66, g1 = 67, g#1 = 68, a1 = 69, a#1 = 70, b1 = 71
c2 = 72

I need script with randomization algorithm/code that will have definible minimal and maximal values for range of randomization.

For example:
If we set 48 as min value and 60 as max value, notes will be randomized between C0 and C1.
(c0, c#0, d0, d#0, e0, f0, f#0, g0, g#0, a0, a#0, b0, c1)
If we set 48 as min value and 72 as max value, notes will be randomized between C0 and C2.
(c0, c#0, d0, d#0, e0, f0, f#0, g0, g#0, a0, a#0, b0, c1, c#1, d1, d#1, e1, f1, f#1, g1, g#1, a1, a#1, b1, c2)
If we set 60 as min value and 72 as max value, notes will be randomized between C1 and C2.
(c1, c#1, d1, d#1, e1, f1, f#1, g1, g#1, a1, a#1, b1, c2)
Etc.
Script with someting like rndvaluemin and rndvaluemax.


> The other three scripts are implemented, you can download them from ReaPack:
> zaibuyidao_Random Mute Notes.lua
> zaibuyidao_Random Notes Start (Customize).lua -- Randomize Notes Position
> zaibuyidao_Random Notes End (Customize).lua -- Randomize Notes Length

AND HUUUUGE THANKS FOR THIS!!!

**Comment by ARkaine2** [comment]
Thanks for
zaibuyidao_Random Notes Pitch (Customize).lua
zaibuyidao_Random Notes Key (Customize).lua
