### ISSUE TITLE
Script that will select notes (in opened MIDI item/take) of the same channel as channel of note under mouse cursor

### ISSUE THREAD

**Issue by ARkaine2** [zaibuyidao/ReaScripts#6]
Sorry for disturbing

![image](https://user-images.githubusercontent.com/31447095/83473657-c70e3900-a492-11ea-8f57-48eeb7a518c4.png)

For example I have 2 MIDI items/takes opened in 1 MIDI Editor.
Item 1 contains blue notes (that are channel 1) and item 2 contains red notes (that are channel 5).
(I prefer to separete notes to different MIDI channels for part editing)
Is it possible to select all red notes (channel 5) when mouse cursor is over one of them?

I know that there's built in MIDI filter in MIDI Editor, 
![image](https://user-images.githubusercontent.com/31447095/83474030-ab576280-a493-11ea-8989-ea610e466476.png)
but it's to complex to use it each time with notes that are multiple channels.

**Comment by zaibuyidao** [comment]
I don't quite agree to use multiple channels in one MIDI editor, it will be very troublesome.

However, the problem you said should be solved. I don’t know how to get the note information when hovering the mouse, but I can select all notes by selecting one of notes (the channel corresponding to the selected note). You can try this script (zaibuyidao_Select All Notes By Note Channel.lua) and start it by shortcut key. You can also use Mouse Modifiers to bind this script for use with the mouse.

![sel note chan](https://user-images.githubusercontent.com/46724195/83808984-42b4f380-a6e8-11ea-90a2-25621191f5d5.png)

**Comment by ARkaine2** [comment]
Thanks. 
That's not problem for me to switch between items/takes or I can glue all of them into one.
You are very helpful.
Thanks you for this.

**Comment by zaibuyidao** [comment]
If you are an item with only one MIDI channel, in fact, you can also use the script (zaibuyidao_Set Events Channel.lua) to set the item MIDI channels to the default 1 Channel. This makes it easy to switch tracks and edit notes.
