### ISSUE TITLE
Glue All Overlapping Notes

### ISSUE THREAD

**Issue by ARkaine2** [zaibuyidao/ReaScripts#8]
Sorry for disturbing.
But I have very necessary for me ask.
Can you please make script something like:
Glue All Overlapping Notes
?
-- as name says it should glue all notes (in media/MIDI item) that are overlapping (each other).

**Comment by zaibuyidao** [comment]
The REAPER has this action:
Edit: Join notes

It is recommended to enable this option:
Options - Automatically correct overlapping notes
