### ISSUE TITLE
Send (increase/decrease value of) MIDI CC script

### ISSUE THREAD

**Issue by ARkaine2** [zaibuyidao/ReaScripts#9]
Sorry for asking for help again.
But I need your help very much.
So, please help, when/if it will be possible.

I'm trying to make PC keyboard send MIDI CC messages (to Reaper / track).
(I have MIDI controller [device], so that's my own need)
I have some progress in it, but i stucked at one step.

ATM I have such script:

```
MIDI_channel = 1
CC = 9
CC_value = 127
reaper.StuffMIDIMessage(0, -- external device 2; 16 is external device 0, 17 is external device 1, etc.
0xB0 + (MIDI_channel - 1), -- this will send a CC message to the selected MIDI channel
CC,
CC_value
)
```

But the problem is that it sends one value (127 in this case).
I need to make it work more like "regular" MIDI controller:
When button is pressed it should increase/decrease MIDI CC value.

So, is it possible to make (probably pair of) script(s), that(those) rise/decrease(s) CC value?

**Comment by zaibuyidao** [comment]
You need to remember the CC value in order to increment or decrement it. Try these two scripts:

```
-- VKB CC valuel -1.lua
MIDI_channel = 1
CC = 9
CC_value = reaper.GetExtState("StuffMIDI", "CCValue") -- Get the extended state value for a specific section and key.
if (CC_value == "") then CC_value = "127" end
CC_value = CC_value - 1
if CC_value < 1 then CC_value = 1 end

reaper.StuffMIDIMessage(0, -- external device 2; 16 is external device 0, 17 is external device 1, etc.
0xB0 + (MIDI_channel - 1), -- this will send a CC message to the selected MIDI channel
CC,
CC_value
)

reaper.SetExtState("StuffMIDI", "CCValue", CC_value, false) -- Set the extended state value for a specific section and key.
```

```
-- VKB CC valuel +1.lua
MIDI_channel = 1
CC = 9
CC_value = reaper.GetExtState("StuffMIDI", "CCValue") -- Get the extended state value for a specific section and key.
if (CC_value == "") then CC_value = "127" end
CC_value = CC_value + 1
if CC_value > 127 then CC_value = 127 end

reaper.StuffMIDIMessage(0, -- external device 2; 16 is external device 0, 17 is external device 1, etc.
0xB0 + (MIDI_channel - 1), -- this will send a CC message to the selected MIDI channel
CC,
CC_value
)

reaper.SetExtState("StuffMIDI", "CCValue", CC_value, false) -- Set the extended state value for a specific section and key.
```

**Comment by ARkaine2** [comment]
Thanks a lot! 
It works perfectly. :)

Even with multiple instruments it moves synchronically. :)
And it's possible to change step.

**Comment by ARkaine2** [comment]
One more question and maybe ask:
Can in such way be made send of Program Change message?

I think that I can remap CC to Program Change with some Reaper Scripts, but faster way is to send Program Change by default.

**Comment by ARkaine2** [comment]
One more question and maybe ask:
Can in such way be made send of Program Change message?
